### ISSUE TITLE
Curious about "published" that I had to remove from Index.vue

### ISSUE THREAD

**Issue by LorenAmelang** [calebanthony/gridsome-bulma#11]
I added a new component to my site, and got tons of build errors. Ended up upgrading Gridsome and all the plugins to @latest. Then got bulma errors, so I merged in your changes from here. Thank you for the updates! 

It all worked, except for:
```
 @ ./src/pages/Index.vue?vue&type=custom&index=0&blockType=page-query 1:0-331 1:347-350 1:352-680 1:352-680
 @ ./src/pages/Index.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/router.js
 @ ./node_modules/gridsome/app/entry.sockjs.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js
 
  error  in ./src/pages/Index.vue?vue&type=custom&index=0&blockType=page-query
 
 Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js):
 Error: Field "published" is not defined by type PostFilterInput.
 
 GraphQL request:19:28
 18 | query {
 19 |   posts: allPost(filter: { published: { eq: true }}) {
    |                            ^
 20 |     edges {
     at Object.module.exports (C:\Users\loren\Documents\Psychoros\Gridsome Test\bulma\node_modules\gridsome\lib\plugins\vue-components\lib\loaders\page-query.js:29:23)
```
My markdown doesn't have any "published" lines, but that doesn't sound like the problem. 

I changed "posts: allPost(filter: { published: { eq: true }})" back to its old, simple form, and everything is working again. But I like to understand things before they bite me again...  

"PostFilterInput" is not found anywhere in my project. I only see "published" deep in various node_modules, nothing in the files that format my site. The only appearance here was in your Index.vue - before I removed it. 

What am I missing?

**Comment by calebanthony** [comment]
You should be able to just remove that filter altogether. So that line looks like:
`posts: allPost() {`

That's just a filter that I added to the query so that people can set `published: true` or `false` to their markdown header so they can have draft posts.

**Comment by LorenAmelang** [comment]
Removing it totally works. So I guess if you leave it in you have to add the "published: true" (or false) line to every post header? But that didn't seem to be what the error said...  Do I need to add "PostFilterInput" somewhere to use this?

**Comment by calebanthony** [comment]
The PostFilterInput is on the Gridsome side to filter posts. It looks for
it in your markdown header and filters by it then.
