### ISSUE TITLE
Can I add WAI-ARIA Accessibility to gridsome-bulma? 

### ISSUE THREAD

**Issue by LorenAmelang** [calebanthony/gridsome-bulma#8]
After a disaster trying to use Gatsby, I found Gridsome and this starter. The layout and colors are great, and I see how to do most of what I need. Many Thanks! 

But my site must be fully WAI-ARIA Accessible, and it doesn't look easy so far...  

https://github.com/jgthms/bulma/issues/53
After over three years of talking about accessibility...  
"I  didn't say it's not a priority ever. I said it is probably not a priority at the moment."

I ran across BootstrapVue in my searches, and added it to my project, but it has destroyed the look of the site! Apparently it is an alternative to Bulma, not an add-on? 

Is there some _simple_ automated way to handle ARIA tagging within gridsome-bulma? 

Should I give up and look for a native Bootstrap starter?

**Comment by LorenAmelang** [comment]
I've been digging into this...  I checked this starter, and several others that mentioned Bootstrap or ARIA, using the ARC Toolkit add-on for Chromium DevTools. Bulma showed more ARIA instances than the others, and way fewer accessibility errors. Looks like the ARIA capability is there, maybe I just need to learn to use it?

**Comment by calebanthony** [comment]
This isn't really a Gridsome thing nor a Bulma thing. It also isn't really something that can be covered by this theme, it would need to happen on the Bulma side of things, but looking at the issue you linked, doesn't seem to be a priority for them.

My recommendation would be to write something yourself, even if it's just a snippet in your IDE, to handle this sort of thing.
